### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by rajegit** [damienpontifex/TypescriptAngular2CodeGen#4]
Wondering how to use it , it does not have any renable ( like npm install ) . how to use it quick liner will help.

Thanks .
Raje

**Comment by damienpontifex** [comment]
This was integrated as part of the main swagger-codegen repo. I didn't do the final integration work, but I have found a few things on how it's expected to be used.

In the file https://github.com/swagger-api/swagger-codegen/blob/master/bin/typescript-angular2-petstore.sh it's called via `swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -o client/petstore -l typescript-angular2` although this doesn't work for me. It throws an error about loading a config class.

This was the PR where it was merge and seems to indicate the library name/parameter should be `typescript-angular2` https://github.com/swagger-api/swagger-codegen/pull/2645 by looking at the `TypeScriptAngular2ClientCodegen.getName()` method.

Sorry, I haven't been using this so can't provide a working sample. I see you have also opened an issue on the swagger-codegen repo, so hopefully they have some insights into why this doesn't work

**Comment by rajegit** [comment]
Thanks for the input @damienpontifex , there is just no info avaliable and  [swagger-api/swagger-codegen#2645](url) was a puzzle for me :) 
This is my best bet on this , I looked in  (https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-angular2/npm) and tried making the required file but its seems I need some help here 
I also opened a ticket with swagger-api here [](https://github.com/swagger-api/swagger-codegen/issues/3221#issuecomment-228676269)

**Comment by damienpontifex** [comment]
@rajegit I have updated swagger-codegen on my computer and noticed the typescript-angular2 is now in there. You can use it after updating by:
```bash
swagger-codegen generate -i http://your-url/swagger.json -o client -l typescript-angular2
```

Hope this helps and give me a shout if you continue to have any issues
